spring:

  application:
    name: back-emprego

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/teste
#    username: postgres
#   password: zaqueu123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          autocommit: false
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  security:
    token:
      secret: "${JWT_SECRET:my-secret-key}"
    cors:
      url: "${CORS_ALLOWED_ORIGINS:http://localhost:4200}"
server:
  tomcat:
    threads:
      max: 200
      min-spare: 10